Repository cgerard321/STQA-pet-clinic-F2020, pull requests merged in 2020-12, with the labels that each got.

#95 bug(APPT-STQA-271): Fix selenium tests
  pom.xml
Labels: APPT

#94 feat(APPT-STQA-221): Fixed Vet Visits Display
  src/main/java/org/springframework/samples/petclinic/repository/VisitRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataVisitRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/webapp/WEB-INF/jsp/appointments/createAppointments.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentTest.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
Labels: APPT

#96 feat(OWRT-STQA-207): Add Show All Owners Button
  src/main/java/org/springframework/samples/petclinic/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcOwnerRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaOwnerRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataOwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/webapp/WEB-INF/jsp/owners/findOwners.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: OWRT

#100 bug(YEET-SQTA-211): Deleting pet with rating throws exception
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcPetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaPetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataPetRepositoryImpl.java
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
Labels: YEET

#105 feat(YEET-SQTA-206): Redesign Pet List Page
  src/main/webapp/WEB-INF/jsp/pets/findPets.jsp
  src/main/webapp/WEB-INF/tags/footer.tag
  src/main/webapp/WEB-INF/tags/htmlHeader.tag
  src/main/webapp/resources/css/petPage.css
  src/main/webapp/resources/javascript/PetPage.js
  src/test/java/org/springframework/samples/petclinic/web/AppointmentTest.java
  src/test/java/org/springframework/samples/petclinic/web/PetPageTest.java
Labels: YEET

#99 feat(COCO-STQA-197) Display Pet Ratings
  src/main/java/org/springframework/samples/petclinic/repository/RatingRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcRatingRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcRatingRowMapper.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaRatingRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/RatingController.java
  src/main/webapp/WEB-INF/jsp/ratings/findPetRatings.jsp
  src/main/webapp/WEB-INF/jsp/ratings/petRatingList.jsp
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/RatingControllerTests.java
Labels: COCO

#112 I added a css file for ownerListTable and connected them. I also
  src/main/webapp/WEB-INF/tags/htmlHeader.tag
  src/main/webapp/resources/css/ownerListTable.css
Labels: OWRT

#103 feat(COCO-STQA-203): Updated the content and links of the footer
  src/main/webapp/WEB-INF/tags/footer.tag
  src/main/webapp/resources/css/footer.css
  src/test/java/org/springframework/samples/petclinic/web/FooterTest.java
Labels: COCO

#107 feat/(COCO-STQA-22): View Calendar Appointments
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/main/webapp/WEB-INF/tags/footer.tag
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/resources/javascript/Calendar.js
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentTest.java
Labels: COCO

#115 Feat(COCO-STQA-20) Show reminders in calendar
  src/main/java/org/springframework/samples/petclinic/model/Event.java
  src/main/java/org/springframework/samples/petclinic/repository/EventRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcEventRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaEventRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataEventRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/util/CalendarHelper.java
  src/main/java/org/springframework/samples/petclinic/web/EventController.java
  src/main/resources/db/hsqldb/initDB.sql
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/main/webapp/resources/javascript/Calendar.js
  src/test/java/org/springframework/samples/petclinic/util/CalendarHelperTest.java
  src/test/java/org/springframework/samples/petclinic/util/CalendarHelperTests.java
Labels: COCO

#119 feat(APPT-STQA-125): Add list of available vets
  src/main/java/org/springframework/samples/petclinic/repository/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataVetRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdateVisitForm.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentTest.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
Labels: APPT

#114 feat/YEET-SQTA-35-Add_Pet_Size
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcPetRepositoryImpl.java
  src/main/resources/db/hsqldb/initDB.sql
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/resources/db/mysql/initDB.sql
  src/main/resources/db/mysql/populateDB.sql
  src/main/resources/db/postgresql/initDB.sql
  src/main/resources/db/postgresql/populateDB.sql
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
  src/main/webapp/WEB-INF/jsp/pets/petDetails.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetPageTest.java
Labels: YEET

#118 bugfix/APPT-STQA-225_Resolve_Bugfix_LastMinuteAppointments
  src/main/java/org/springframework/samples/petclinic/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/resources/db/mysql/populateDB.sql
  src/test/java/org/springframework/samples/petclinic/model/VetTests.java
Labels: APPT

#117 Feat(OWRT-STQA-208): Sort_Owner_List_By_Name
  src/main/java/org/springframework/samples/petclinic/util/SortingUtils.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
  src/test/java/org/springframework/samples/petclinic/util/SortingUtilsTest.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: OWRT

#116 Feat(COCO-STQA-205): Use Pet Ratings
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
Labels: COCO

#121 Feat/(APPT-STQA-123): update schedule v2
  src/main/java/org/springframework/samples/petclinic/model/Schedule.java
  src/main/java/org/springframework/samples/petclinic/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/repository/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/webapp/WEB-INF/jsp/vets/modifySchedule.jsp
  src/main/webapp/WEB-INF/jsp/vets/scheduleList.jsp
  src/main/webapp/resources/less/petclinic.less
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
Labels: APPT

#123 feat/COCO-STQA-292 Add Missing Button To Welcome Page
  src/main/webapp/WEB-INF/jsp/welcome.jsp
Labels: COCO
