Repository cgerard321/STQA-pet-clinic-F2020, pull requests merged in 2020-11, with the labels that each got.

#36 feat(OWRT-STQA-72) : Add new email field
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcOwnerRepositoryImpl.java
  src/main/resources/db/hsqldb/initDB.sql
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/webapp/WEB-INF/jsp/.DS_Store
  src/main/webapp/WEB-INF/jsp/owners/createOrUpdateOwnerForm.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: OWRT

#37 feat(YEET-SQTA-28): See All Pets
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/model/VetSchedule.java
  src/main/java/org/springframework/samples/petclinic/repository/PetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcOwnerRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcPet.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcPetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaPetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVetScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/VetScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/webapp/WEB-INF/jsp/.DS_Store
  src/main/webapp/WEB-INF/jsp/pets/petList.jsp
  src/main/webapp/WEB-INF/jsp/vets/saveVetSchedule.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
Labels: YEET

#40 feat(APPT-STQA-74): Added the appointment booking web page (layout)
  src/main/java/org/springframework/samples/petclinic/model/VetSchedule.java
  src/main/java/org/springframework/samples/petclinic/repository/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcOwnerRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVetScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/web/CrashController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetValidator.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/java/org/springframework/samples/petclinic/web/VisitController.java
  src/main/webapp/WEB-INF/jsp/appointments/appointments.jsp
  src/main/webapp/WEB-INF/jsp/appointments/createAppointments.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/web/AppointmentControllerTest.java
Labels: APPT

#44 Feat(COCO-STQA-17): Added Navigation Links to the footer
  pom.xml
  src/main/webapp/WEB-INF/tags/footer.tag
  src/main/webapp/WEB-INF/tags/htmlHeader.tag
  src/main/webapp/resources/css/footer.css
  src/test/java/org/springframework/samples/petclinic/web/FooterTest.java
Labels: COCO

#45 feat(APPT-SQTA-34): View All Vet Schedules and Find schedule by vet Id
  pom.xml
  src/main/java/org/springframework/samples/petclinic/model/Schedule.java
  src/main/java/org/springframework/samples/petclinic/model/Schedules.java
  src/main/java/org/springframework/samples/petclinic/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/model/VetSchedule.java
  src/main/java/org/springframework/samples/petclinic/repository/ScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcPetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcScheduleRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaPetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaScheduleRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVetScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/VetScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/ScheduleController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/resources/db/hsqldb/initDB.sql
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/resources/db/mysql/initDB.sql
  src/main/resources/db/mysql/populateDB.sql
  src/main/webapp/WEB-INF/jsp/vets/displaySchedule.jsp
  src/main/webapp/WEB-INF/jsp/vets/saveVetSchedule.jsp
  src/main/webapp/WEB-INF/jsp/vets/scheduleList.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
  src/main/webapp/WEB-INF/tags/htmlHeader.tag
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/resources/css/foundation-icons/foundation-icons.css
  src/main/webapp/resources/css/foundation-icons/foundation-icons.svg
  src/main/webapp/resources/css/foundation-icons/preview.html
  src/main/webapp/resources/css/headerPage.css
  src/main/webapp/resources/less/petclinic.less
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/ScheduleControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
Labels: APPT

#51 Feat(COCO-STQA-17)Fixed footer across multiple pages
  src/main/webapp/resources/css/footer.css
Labels: COCO

#54 Bug(APPT-STQA-34): Bug in "View all owner"
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaScheduleRepositoryImpl.java
Labels: APPT

#56 feat(YEET-STQA-55):Pet_Information
  src/main/java/org/springframework/samples/petclinic/util/DateMethods.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/pets/petDetails.jsp
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
Labels: YEET

#23 feat(YEET-SQTA-70):Display_Pet_Page
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/webapp/WEB-INF/jsp/pets/findPets.jsp
  src/main/webapp/WEB-INF/jsp/pets/petList.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
Labels: YEET

#53 feat(Yeet-SQTA-27): Remove Pet
  src/main/java/org/springframework/samples/petclinic/PetclinicInitializer.java
  src/main/java/org/springframework/samples/petclinic/repository/PetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcPetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaPetRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataPetRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/webapp/WEB-INF/jsp/appointments/appointments.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentControllerTest.java
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
Labels: YEET

#46 feat(APPT-STQA-41): add pet owner cancel appointment
  src/main/java/org/springframework/samples/petclinic/repository/VisitRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataVisitRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/webapp/WEB-INF/jsp/appointments/cancelAppointment.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: APPT

#52 feat(APPT-SQTA) View All Appointments 1.0
  src/main/java/org/springframework/samples/petclinic/repository/VisitRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/webapp/WEB-INF/jsp/appointments/viewAppointments.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentControllerTest.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/VisitControllerTests.java
Labels: APPT

#65 feat(APPT-STQA-122): Allow Vets to have multiple days on schedule
  src/main/java/org/springframework/samples/petclinic/model/Schedule.java
  src/main/java/org/springframework/samples/petclinic/model/Schedules.java
  src/main/java/org/springframework/samples/petclinic/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/repository/ScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcScheduleRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaScheduleRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataScheduleRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/ScheduleController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/resources/db/hsqldb/initDB.sql
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/resources/db/mysql/initDB.sql
  src/main/resources/db/mysql/populateDB.sql
  src/main/webapp/WEB-INF/jsp/vets/displaySchedule.jsp
  src/main/webapp/WEB-INF/jsp/vets/scheduleList.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
  src/test/java/org/springframework/samples/petclinic/web/ScheduleControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
Labels: APPT

#67 feat/APPT_STQA_145_View_Appointments_Cancel_And_Filter
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
  src/main/java/org/springframework/samples/petclinic/repository/VisitRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/jpa/JpaVisitRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataPetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataVisitRepository.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicService.java
  src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/webapp/WEB-INF/jsp/appointments/viewAppointments.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentControllerTest.java
Labels: APPT

#64 feat/YEET-SQTA-130-Edit_Pet_Information
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
  src/main/webapp/WEB-INF/jsp/pets/findPets.jsp
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
Labels: YEET

#63 Feat/owrt stqa 73 add owner comment
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/resources/db/hsqldb/initDB.sql
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/resources/db/mysql/initDB.sql
  src/main/resources/db/mysql/populateDB.sql
  src/main/resources/db/postgresql/initDB.sql
  src/main/resources/db/postgresql/populateDB.sql
  src/main/webapp/WEB-INF/jsp/owners/createOrUpdateOwnerForm.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: OWRT

#73 bug(STQA-190): Fix functionality with non-default TomCat prefix
  src/main/webapp/WEB-INF/jsp/appointments/viewAppointments.jsp
  src/main/webapp/WEB-INF/jsp/pets/findPets.jsp
  src/main/webapp/WEB-INF/tags/footer.tag
  src/test/java/org/springframework/samples/petclinic/web/AppointmentControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/AppointmentTest.java
  src/test/java/org/springframework/samples/petclinic/web/FooterTest.java
  src/test/java/org/springframework/samples/petclinic/web/WebTestsCommon.java
Labels: APPT, COCO, YEET

#77 feat(APPT-STQA-118): Add a back button to the appointment cancel page
  src/main/webapp/WEB-INF/jsp/appointments/cancelAppointment.jsp
  src/test/java/org/springframework/samples/petclinic/web/AppointmentTest.java
Labels: APPT

#78 Feat/yeet stqa 126 link pet information to pet page
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/webapp/WEB-INF/jsp/pets/findPets.jsp
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
Labels: YEET

#81 feat(APPT-STQA-136): Add input validation to owner cancel form
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/webapp/WEB-INF/jsp/pets/findPets.jsp
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: APPT

#74 feat(OWRT-STQA-127) : Improve_Input_Fields_Validation
  pom.xml
  src/main/java/org/springframework/samples/petclinic/annotation/ValidAddress.java
  src/main/java/org/springframework/samples/petclinic/annotation/ValidCity.java
  src/main/java/org/springframework/samples/petclinic/annotation/ValidName.java
  src/main/java/org/springframework/samples/petclinic/annotation/ValidPhoneNumber.java
  src/main/java/org/springframework/samples/petclinic/annotation/ValidState.java
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/model/Person.java
  src/main/java/org/springframework/samples/petclinic/repository/jdbc/JdbcOwnerRepositoryImpl.java
  src/main/java/org/springframework/samples/petclinic/validator/OwnerAddressValidator.java
  src/main/java/org/springframework/samples/petclinic/validator/OwnerCityValidator.java
  src/main/java/org/springframework/samples/petclinic/validator/OwnerNameValidator.java
  src/main/java/org/springframework/samples/petclinic/validator/OwnerPhoneValidator.java
  src/main/java/org/springframework/samples/petclinic/validator/OwnerStateValidator.java
  src/main/resources/db/hsqldb/initDB.sql
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/webapp/WEB-INF/jsp/owners/createOrUpdateOwnerForm.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: OWRT

#86 Added a last minute Appointment page
  src/main/java/org/springframework/samples/petclinic/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/web/AppointmentController.java
  src/main/webapp/WEB-INF/jsp/appointments/lastMinuteAppointments.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
Labels: APPT

#83 Feat/owrt stqa 77 add picture of owner
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/resources/db/hsqldb/initDB.sql
  src/main/resources/db/hsqldb/populateDB.sql
  src/main/resources/db/mysql/initDB.sql
  src/main/resources/db/mysql/populateDB.sql
  src/main/resources/db/postgresql/initDB.sql
  src/main/resources/db/postgresql/populateDB.sql
  src/main/webapp/WEB-INF/jsp/owners/createOrUpdateOwnerForm.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
  src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
Labels: OWRT

#90 feat(APPT-STQA-122): Vet Schedule Sorted
  src/main/java/org/springframework/samples/petclinic/model/Vet.java
Labels: APPT
