Repository cgerard321/STQA-pet-clinic-F2020, pull requests merged in 2020-10, with the labels that each got.

#2 chore(STQA-000): update readme
  README.md
Labels: Config

#3 config(STQA-000): add maven CI
  .github/workflows/maven.yml
Labels: Config

#9 feat(TEAMA-STQA-4): Added a test message
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
Labels: Config

#11 feat(APPT-SQTA-34-VET-SET-SCHEDULES): Test Comment
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
Labels: APPT

#19 feat(OWRT-STQA-54): Added a comment
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
Labels: OWRT

#16 feat(YEET-STQA-28): Added a funny comment
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
Labels: YEET

#17 Feat(owrt-stqa-43): Added 2 comments as a test
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
Labels: OWRT

#18 feat(Yeet-STQA-4): Added a test comment in PetType model
  src/main/java/org/springframework/samples/petclinic/model/PetType.java
Labels: YEET

#20 feat(COCO-STQA-17: Added a Note to footer.tag
  src/main/webapp/WEB-INF/tags/footer.tag
Labels: COCO

#13 feat(OWRT-STQA-54): Added a test message
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
Labels: OWRT
